### ISSUE TITLE
VL_IO_2D_xx are not exported in final library

### ISSUE THREAD

**Issue by Christophe-ABEL** [MicBosi/VisualizationLibrary#179]
Hello,
I try to use VL 2.0 with static Library.
I work with QT5.15.1 and mingw 8.1 win32.

For example, when I set VL_IO_2D_JPG to ON, I obtain a library called libJPG-d-a and in released mode libJPG-a
But when i tried to use it within my application i have a compilation error:

71: erreur : undefined reference to `vl::loadJPG(vl::String const&)'

it seems that with the default CMakesLists files of VL, ioJPG.cpp and  ioJPG.hpp are not take into account to produce the final library (nothing within libVLCore or libJPG)

This problem appears with all files of vlCore/Plugin and with vlGraphics/Plugins too.

is there something to add somwhere to generate a good library (perhaps in vlCore/Plugins/CMakesLists.txt?)

thanks in advance for help

Christophe
