### ISSUE TITLE
New template constructors for Vector2, Vector3, and Vector4 cause build error when compiled with g++ 7.5.0

### ISSUE THREAD

**Issue by deadmorous** [MicBosi/VisualizationLibrary#194]
Hi, I've been using VL version v2.0-β2, and now tried to switch to the new version 2.1.

The new version does not build with g++ 7.5.0. The reason is the new constructors in Vector2, Vector3, and Vector4, those that specialize the templated constructor. The error messages are like

`VisualizationLibrary/src/vlCore/Vector2.hpp:113:14: error: explicit specialization in non-namespace scope ‘class vl::Vector2<T_Scalar>’
`
Removing `template<>` seems to solve this problem, but I didn't try newer compiles.

Regards,
Stepan Orlov

**Comment by FabienMathieu** [comment]
Hi, 

I noticed the same thing.
I added an PR some days ago, waiting for it to be accepted.

Regards

Fabien MATHIEU

**Comment by deadmorous** [comment]
Ok, found your PR. Lets then wait for it to get merged.
